services:
  pgsql:
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: yiitest
    ports:
      # <Port exposed> : <PGSQL Port running inside container>
      - 5432:5432
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
